name: mlops-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train  my model'
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
